"""@package graph_api

@brief Python server for the graph API.

This module contains the code for the graph API, which is used to generate
the graphs for the students' information.
"""

import pandas as pd
import plotly.express as px
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from starlette.responses import RedirectResponse

graphAPI = FastAPI()

graphAPI.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@graphAPI.get("/")
async def root():
    """
    When the server is running, the root path will redirect to
    the OpenAPI docs generated by FastAPI.
    """
    return RedirectResponse(url="/docs")


class Student(BaseModel):
    """Data model containing the student's relevant information.

    Attributes:
        name (str): Student name.
        uaslp_key (str): Student UASLP key, unique identifier.
        large_key (str): Student large key, as defined in the docs.
        status (str): Student status, either "INSCRITO" or "NO INSCRITO".
        semesters_completed (int): Number of semesters completed.
        creds_per_semester (int): Number of credits per semester.
        app_average (float): Student average approvatory. grade.
    """
    name: str
    uaslp_key: str
    large_key: str
    status: str
    generation: str
    semesters_completed: int
    creds_per_semester: float
    app_average: float


class StudentList(BaseModel):
    """List of students

    Permits to simplify the API call, as well as the pydantic validation.

    Attributes:
        records (list): List of students.
    """
    records: list[Student]


def get_dataframe(student_list: StudentList) -> pd.DataFrame:
    """Converts a list of students into a pandas DataFrame.

    Converts the list of students into a pandas DataFrame, and also calculates:
        - `cred_app_acum`, which is the total number of credits approved
        by the student.
        - `cred_rezago`, which is the number of credits behind the student
        is compared to the expected number of credits.
        - `nivel_rezago`, which is the level of delay of the student, either
        "Sin rezago", "Rezago leve" or "Rezago grave".

    Args:
        student_list (StudentList): List of students.

    Returns:
        pd.DataFrame: DataFrame containing the students' information.
    """

    data_frame = pd.DataFrame.from_records(
        map(lambda student: student.dict(), student_list.records)
    )

    data_frame["cred_app_acum"] = (
        data_frame["semesters_completed"] * data_frame["creds_per_semester"]
    )

    data_frame["cred_rezago"] = (
        data_frame["semesters_completed"] * 45 - data_frame["cred_app_acum"]
    )

    data_frame["nivel_rezago"] = data_frame["cred_rezago"].apply(
        lambda cred_rezago: (
            "Sin rezago"
            if cred_rezago <= 0
            else "Rezago leve"
            if cred_rezago <= 20
            else "Rezago grave"
        )
    )

    return data_frame


@graphAPI.post("/graph/scatter")
async def scatter_plot(data: StudentList):
    """Generates a scatter plot.

    Generates a scatter plot for the students' approved credits and
    their average approvatory grade.
    The plot is generated using plotly.express.

    Args:
        data (StudentList): List of students.

    Returns:
        str: JSON containing the information to render the plot.
    """

    data_frame = get_dataframe(data)

    fig = px.scatter(
        data_frame,
        x="cred_app_acum",
        y="app_average",
        labels={
            "cred_app_acum": "Créditos aprobados acumulados",
            "app_average": "Promedio aprobatorio",
            "generation": "Generación",
            "status": "Estatus",
            "name": "Nombre",
            "uaslp_key": "Clave única",
            "large_key": "Clave larga de la facultad",
            "color": "Generación",
        },
        color="generation",
        color_discrete_sequence=px.colors.qualitative.G10,
        hover_name="name",
        hover_data=["uaslp_key", "large_key", "status"],
    )

    return fig.to_json()


@graphAPI.post("/graph/bar")
async def bar_plot(data: StudentList):
    """Generates a bar plot.

    Generates a bar plot for the students' group by their generation and
    their level of delay. The plot is generated using plotly.express.

    Args:
        data (StudentList): List of students.

    Returns:
        str: JSON containing the information to render the plot.
    """
    data_frame = get_dataframe(data)

    fig = px.histogram(
        data_frame,
        x="generation",
        color="nivel_rezago",
        labels={
            "generation": "Generación",
            "nivel_rezago": "Nivel de rezago",
        },
        color_discrete_map={
            "Sin rezago": "rgb(0, 255, 0)",
            "Rezago leve": "rgb(255, 255, 0)",
            "Rezago grave": "rgb(255, 0, 0)",
        },
        hover_name="name",
    )

    return fig.to_json()
